name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Needed to checkout the repository
      packages: write # Needed to push Docker images to ghcr.io
      attestations: write # Optional: if you plan to create attestations for your image
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/multidrawer:latest .
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}/multidrawer:latest
